name: PrivateStorage
version: ${project.version}
author: TheBusyBiscuit

main: io.github.thebusybiscuit.privatestorage.PrivateStorage
api-version: 1.14

depend: [Slimefun]

permissions:
  PrivateStorage.bypass:
    description: Allows to open all Safes
    default: false